CREATE TABLE IF NOT EXISTS USERS(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    passwd VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TASKS(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    descript TEXT NULL,
    deadline TIMESTAMP NULL,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);
